
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | emptyhandleheader : OPENHEADER CONTENT CLOSEHEADER handleheader\n                    | OPENHEADER CONTENT CLOSEHEADER dataCell\n                    | emptydataCell_empty : emptydataCell : OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty\n                    | OPENDATA OPENHREF CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty\n                    | OPENDATA OPENHREF CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty\n                    | OPENDATA OPENHREF CONTENT CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty\n                    | OPENDATA CLOSEDATA dataCell\n                    | OPENDATA CONTENT CLOSEDATA dataCell\n                    | OPENDATA CLOSEDATA handleheader\n                    | emptyhandlerow : OPENROW handleheader CLOSEROW handlerow \n                 | OPENROW dataCell CLOSEROW handlerow\n                 | emptytable : BEGINTABLE skiptag OPENTABLE handlerow empty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,9,13,15,21,22,27,28,],[0,-1,-22,-21,-20,-22,-22,-18,-19,]),'CONTENT':([3,5,6,7,18,20,24,30,37,48,49,51,54,60,65,67,70,72,77,79,82,84,89,91,94,96,101,103,106,],[5,5,5,5,23,25,30,37,41,52,53,55,58,64,69,71,74,76,81,83,86,88,93,95,98,100,105,107,111,]),'OPENHREF':([3,5,6,7,20,46,48,50,],[6,6,6,6,24,49,51,54,]),'CLOSEHREF':([3,5,6,7,30,37,41,53,55,58,],[7,7,7,7,38,42,44,57,59,62,]),'OPENTABLE':([3,4,5,6,7,8,10,11,12,],[-22,9,-22,-22,-22,-5,-2,-3,-4,]),'OPENROW':([9,21,22,],[14,14,14,]),'OPENHEADER':([14,26,29,],[18,18,18,]),'OPENDATA':([14,26,29,31,43,45,47,56,61,63,66,68,73,75,78,80,85,87,90,92,97,99,102,],[20,20,20,20,46,48,50,60,65,67,70,72,77,79,82,84,89,91,94,96,101,103,106,]),'CLOSEROW':([14,16,17,19,26,29,31,32,33,34,35,36,39,40,104,108,109,110,112,113,114,115,116,],[-22,21,22,-8,-22,-22,-22,-14,-16,-8,-6,-7,-15,-17,-22,-12,-9,-22,-22,-10,-22,-11,-13,]),'CLOSEDATA':([20,25,38,42,44,52,57,59,62,64,69,71,74,76,81,83,86,88,93,95,98,100,105,107,111,],[26,31,43,45,47,56,61,63,66,68,73,75,78,80,85,87,90,92,97,99,102,104,110,112,114,]),'CLOSEHEADER':([23,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,],[4,10,11,12,]),'empty':([3,5,6,7,9,14,21,22,26,29,31,104,110,112,114,],[8,8,8,8,15,19,15,15,34,19,40,109,109,109,109,]),'handlerow':([9,21,22,],[13,27,28,]),'handleheader':([14,26,29,],[16,33,35,]),'dataCell':([14,26,29,31,],[17,32,36,39,]),'dataCell_empty':([104,110,112,114,],[108,113,115,116,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','23CS60R22_DesLab_T2_C3.py',89),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','23CS60R22_DesLab_T2_C3.py',93),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','23CS60R22_DesLab_T2_C3.py',94),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','23CS60R22_DesLab_T2_C3.py',95),
  ('skiptag -> empty','skiptag',1,'p_skiptag','23CS60R22_DesLab_T2_C3.py',96),
  ('handleheader -> OPENHEADER CONTENT CLOSEHEADER handleheader','handleheader',4,'p_handleheader','23CS60R22_DesLab_T2_C3.py',99),
  ('handleheader -> OPENHEADER CONTENT CLOSEHEADER dataCell','handleheader',4,'p_handleheader','23CS60R22_DesLab_T2_C3.py',100),
  ('handleheader -> empty','handleheader',1,'p_handleheader','23CS60R22_DesLab_T2_C3.py',101),
  ('dataCell_empty -> empty','dataCell_empty',1,'p_dataCell_empty','23CS60R22_DesLab_T2_C3.py',104),
  ('dataCell -> OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty','dataCell',23,'p_dataCell','23CS60R22_DesLab_T2_C3.py',107),
  ('dataCell -> OPENDATA OPENHREF CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty','dataCell',24,'p_dataCell','23CS60R22_DesLab_T2_C3.py',108),
  ('dataCell -> OPENDATA OPENHREF CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty','dataCell',22,'p_dataCell','23CS60R22_DesLab_T2_C3.py',109),
  ('dataCell -> OPENDATA OPENHREF CONTENT CONTENT CONTENT CLOSEHREF CLOSEDATA OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA OPENDATA CONTENT CLOSEDATA dataCell_empty','dataCell',25,'p_dataCell','23CS60R22_DesLab_T2_C3.py',110),
  ('dataCell -> OPENDATA CLOSEDATA dataCell','dataCell',3,'p_dataCell','23CS60R22_DesLab_T2_C3.py',111),
  ('dataCell -> OPENDATA CONTENT CLOSEDATA dataCell','dataCell',4,'p_dataCell','23CS60R22_DesLab_T2_C3.py',112),
  ('dataCell -> OPENDATA CLOSEDATA handleheader','dataCell',3,'p_dataCell','23CS60R22_DesLab_T2_C3.py',113),
  ('dataCell -> empty','dataCell',1,'p_dataCell','23CS60R22_DesLab_T2_C3.py',114),
  ('handlerow -> OPENROW handleheader CLOSEROW handlerow','handlerow',4,'p_handlerow','23CS60R22_DesLab_T2_C3.py',145),
  ('handlerow -> OPENROW dataCell CLOSEROW handlerow','handlerow',4,'p_handlerow','23CS60R22_DesLab_T2_C3.py',146),
  ('handlerow -> empty','handlerow',1,'p_handlerow','23CS60R22_DesLab_T2_C3.py',147),
  ('table -> BEGINTABLE skiptag OPENTABLE handlerow','table',4,'p_table','23CS60R22_DesLab_T2_C3.py',150),
  ('empty -> <empty>','empty',0,'p_empty','23CS60R22_DesLab_T2_C3.py',153),
  ('content -> CONTENT','content',1,'p_content','23CS60R22_DesLab_T2_C3.py',157),
  ('content -> empty','content',1,'p_content','23CS60R22_DesLab_T2_C3.py',158),
]
