
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | emptyhandleheader : OPENHEADER CONTENT CLOSEHEADER handleheader\n                    | emptydataCell : OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA dataCell\n    \t\t| OPENDATA CONTENT OPENHREF CONTENT CLOSEHREF CLOSEDATA dataCell\n                | OPENDATA CONTENT CLOSEDATA dataCell\n                | OPENDATA CLOSEDATA dataCell\n                | handlerow : OPENROW handleheader CLOSEROW handlerow \n                 | OPENROW dataCell CLOSEROW handlerow\n                 | emptytable : BEGINTABLE skiptag OPENTABLE handlerow empty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,9,13,15,21,22,27,28,],[0,-1,-17,-16,-15,-17,-17,-13,-14,]),'CONTENT':([3,5,6,7,18,20,24,31,],[5,5,5,5,23,25,30,36,]),'OPENHREF':([3,5,6,7,20,25,],[6,6,6,6,24,31,]),'CLOSEHREF':([3,5,6,7,30,36,],[7,7,7,7,35,39,]),'OPENTABLE':([3,4,5,6,7,8,10,11,12,],[-17,9,-17,-17,-17,-5,-2,-3,-4,]),'OPENROW':([9,21,22,],[14,14,14,]),'OPENHEADER':([14,29,],[18,18,]),'OPENDATA':([14,26,32,38,41,],[20,20,20,20,20,]),'CLOSEROW':([14,16,17,19,26,29,32,33,34,37,38,40,41,42,],[-12,21,22,-7,-12,-17,-12,-11,-6,-10,-12,-8,-12,-9,]),'CLOSEDATA':([20,25,35,39,],[26,32,38,41,]),'CLOSEHEADER':([23,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,],[4,10,11,12,]),'empty':([3,5,6,7,9,14,21,22,29,],[8,8,8,8,15,19,15,15,19,]),'handlerow':([9,21,22,],[13,27,28,]),'handleheader':([14,29,],[16,34,]),'dataCell':([14,26,32,38,41,],[17,33,37,40,42,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','2.py',87),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','2.py',91),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','2.py',92),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','2.py',93),
  ('skiptag -> empty','skiptag',1,'p_skiptag','2.py',94),
  ('handleheader -> OPENHEADER CONTENT CLOSEHEADER handleheader','handleheader',4,'p_handleheader','2.py',97),
  ('handleheader -> empty','handleheader',1,'p_handleheader','2.py',98),
  ('dataCell -> OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA dataCell','dataCell',6,'p_dataCell','2.py',103),
  ('dataCell -> OPENDATA CONTENT OPENHREF CONTENT CLOSEHREF CLOSEDATA dataCell','dataCell',7,'p_dataCell','2.py',104),
  ('dataCell -> OPENDATA CONTENT CLOSEDATA dataCell','dataCell',4,'p_dataCell','2.py',105),
  ('dataCell -> OPENDATA CLOSEDATA dataCell','dataCell',3,'p_dataCell','2.py',106),
  ('dataCell -> <empty>','dataCell',0,'p_dataCell','2.py',107),
  ('handlerow -> OPENROW handleheader CLOSEROW handlerow','handlerow',4,'p_handlerow','2.py',114),
  ('handlerow -> OPENROW dataCell CLOSEROW handlerow','handlerow',4,'p_handlerow','2.py',115),
  ('handlerow -> empty','handlerow',1,'p_handlerow','2.py',116),
  ('table -> BEGINTABLE skiptag OPENTABLE handlerow','table',4,'p_table','2.py',119),
  ('empty -> <empty>','empty',0,'p_empty','2.py',123),
  ('content -> CONTENT','content',1,'p_content','2.py',127),
  ('content -> empty','content',1,'p_content','2.py',128),
]
