
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT ENDTABLE GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLE PTAGCLOSE PTAGOPENstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | PTAGCLOSE skiptag\n               | emptyhandleheader : OPENHEADER CONTENT CLOSEHEADER handleheader\n                    | emptydataCell : CONTENT dataCell\n                | empty\n                 handlerow : PTAGOPEN dataCell PTAGCLOSE skiptag handlerow\n                | emptytable : BEGINTABLE skiptag handlerow ENDTABLE empty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,17,],[0,-1,-13,]),'CONTENT':([3,5,6,7,8,11,19,21,],[5,5,5,5,5,19,19,5,]),'OPENHREF':([3,5,6,7,8,21,],[6,6,6,6,6,6,]),'CLOSEHREF':([3,5,6,7,8,21,],[7,7,7,7,7,7,]),'PTAGCLOSE':([3,5,6,7,8,11,18,19,20,21,22,],[8,8,8,8,8,-14,21,-14,-10,8,-9,]),'PTAGOPEN':([3,4,5,6,7,8,9,13,14,15,16,21,23,],[-14,11,-14,-14,-14,-14,-6,-2,-3,-4,-5,-14,11,]),'ENDTABLE':([3,4,5,6,7,8,9,10,12,13,14,15,16,21,23,24,],[-14,-14,-14,-14,-14,-14,-6,17,-12,-2,-3,-4,-5,-14,-14,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,8,21,],[4,13,14,15,16,23,]),'empty':([3,4,5,6,7,8,11,19,21,23,],[9,12,9,9,9,9,20,20,9,12,]),'handlerow':([4,23,],[10,24,]),'dataCell':([11,19,],[18,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','23CS60R22_CL2_A3_T1.py',109),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','23CS60R22_CL2_A3_T1.py',113),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','23CS60R22_CL2_A3_T1.py',114),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','23CS60R22_CL2_A3_T1.py',115),
  ('skiptag -> PTAGCLOSE skiptag','skiptag',2,'p_skiptag','23CS60R22_CL2_A3_T1.py',116),
  ('skiptag -> empty','skiptag',1,'p_skiptag','23CS60R22_CL2_A3_T1.py',117),
  ('handleheader -> OPENHEADER CONTENT CLOSEHEADER handleheader','handleheader',4,'p_handleheader','23CS60R22_CL2_A3_T1.py',120),
  ('handleheader -> empty','handleheader',1,'p_handleheader','23CS60R22_CL2_A3_T1.py',121),
  ('dataCell -> CONTENT dataCell','dataCell',2,'p_dataCell','23CS60R22_CL2_A3_T1.py',126),
  ('dataCell -> empty','dataCell',1,'p_dataCell','23CS60R22_CL2_A3_T1.py',127),
  ('handlerow -> PTAGOPEN dataCell PTAGCLOSE skiptag handlerow','handlerow',5,'p_handlerow','23CS60R22_CL2_A3_T1.py',139),
  ('handlerow -> empty','handlerow',1,'p_handlerow','23CS60R22_CL2_A3_T1.py',140),
  ('table -> BEGINTABLE skiptag handlerow ENDTABLE','table',4,'p_table','23CS60R22_CL2_A3_T1.py',151),
  ('empty -> <empty>','empty',0,'p_empty','23CS60R22_CL2_A3_T1.py',154),
  ('content -> CONTENT','content',1,'p_content','23CS60R22_CL2_A3_T1.py',158),
  ('content -> empty','content',1,'p_content','23CS60R22_CL2_A3_T1.py',159),
]
